<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MMO.Protocol</RootNamespace>
    <AssemblyName>Protocol</AssemblyName>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>

    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
  </PropertyGroup>

</Project>